### Add a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "New Blog Title",
  "author": "Author Name",
  "url": "http://example.com",
  "likes": 0
}
